<?php

namespace Core\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatMenuRepository extends EntityRepository
{
}
