<?php

namespace Core\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Core\PlanBundle\Entity\Plan;
use Core\PlanBundle\Entity\Momento;

/**
 * PlanMomentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanMomentoRepository extends EntityRepository
{
    public function findByPlanAndMomento(Plan $plan, Momento $momento)
    {
        return $this->createQueryBuilder('plan_momento')
                    ->leftJoin('plan_momento.menus', 'menu')
//                    ->addSelect('memu')
                    ->leftJoin('plan_momento.plan', 'plan')
                    ->andWhere(sprintf('plan.id = %s', $plan->getId()))
                    ->leftJoin('plan_momento.momento', 'momento')
                    ->andWhere(sprintf('momento.id = %s', $momento->getId()))
               ;
    }
}
