<?php

namespace Core\PlanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    public function findPorFecha(\DateTime $fecha)
    {
        return $this->createQueryBuilder('plan')
                    ->leftJoin('plan.plan_momento', 'plan_momento')
                    ->leftJoin('plan_momento.momento', 'momento')
                    ->leftJoin('plan_momento.menus', 'menu')
                    ->addSelect('plan_momento')
                    ->addSelect('menu')
                    ->addSelect('momento')
                    ->where(sprintf('plan.fecha = \'%s\'', $fecha->format('Y-m-d')))
               ;
    }
}
