parameters:
  cache_max_tiempo: 600

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: menu.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     "%kernel.root_dir%/data/dev.db"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
fos_user:
    db_driver:     orm
    firewall_name: db_user
    user_class:    Core\UserBundle\Entity\User

vich_uploader:
    db_driver: orm
    mappings:
        plato_foto:
            delete_on_remove:   true
            namer:              vich_aleatorio_mamer
            uri_prefix:         /uploads/platos
            upload_destination: %kernel.root_dir%/../web/uploads/platos
            inject_on_load:     false
        menu_foto:
            delete_on_remove:   true
            namer:              vich_aleatorio_mamer
            uri_prefix:         /uploads/menu
            upload_destination: %kernel.root_dir%/../web/uploads/menu
            inject_on_load:     false
            
avalanche_imagine:
    filters:
        list_admin:
            type:    thumbnail
            options: { size: [120, 90], mode: outbound }
        list_front:
            type:    thumbnail
            options: { size: [300, 200], mode: outbound }
        list_miniatura_front:
            type:    thumbnail
            options: { size: [200, 100], mode: outbound }
        show_menor_front:
            type:    thumbnail
            options: { size: [400, 300], mode: outbound }
        show_front:
            type:    thumbnail
            options: { size: [500, 400], mode: outbound }
        destacado_front:
            type:    thumbnail
            options: { size: [200, 100], mode: outbound }
            
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
      default:
        sluggable: true