<?php

namespace Core\PlatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatIngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatIngredienteRepository extends EntityRepository
{
}
