<?php

namespace Core\PlatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRepository extends EntityRepository
{
    public function ingredientesQuery()
    {
        return $this->createQueryBuilder('ingrediente')
                    ->leftJoin('ingrediente.categoria', 'categoria')
                    ->addSelect('categoria')
        ;
    }
    public function findIngredientesQuery(Plato $plato)
    {
        return $this->createQueryBuilder('ingrediente')
                    ->leftJoin('ingrediente.plato_ingredientes', 'plato_ingrediente')
                    ->leftJoin('plato_ingrediente.plato', 'plato')
                    ->where(sprintf('plato.id = %s', $plato->getId()))
               ;
    }
}
