<?php

namespace Core\PlatoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Core\PlanBundle\Entity\Plan;

/**
 * PlatoIngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoIngredienteRepository extends EntityRepository
{
    public function findByPlanQuery(Plan $plan)
    {
        return $this->createQueryBuilder('plato_ingrediente')
                    ->leftJoin('plato_ingrediente.ingrediente', 'ingrediente')
                    ->addSelect('ingrediente')
                    ->leftJoin('plato_ingrediente.plato', 'plato')
                    ->leftJoin('plato.menus', 'menu')
                    ->leftJoin('menu.plan_momentos', 'plan_momento')
                    ->leftJoin('plan_momento.plan', 'plan')
                    ->where(sprintf('plan.id = %s', $plan->getId()))
               ;
    }
}
