<?php

namespace Core\PlatoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatoRepository extends EntityRepository
{
    public function getBySlug($slug)
    {
        return $this->createQueryBuilder('plato')
                    ->where(sprintf('plato.slug = \'%s\'', $slug))
                    ->leftJoin('plato.plato_ingredientes', 'plato_ingrediente')
                    ->leftJoin('plato_ingrediente.ingrediente', 'ingrediente')
                    ->addSelect('plato_ingrediente')
                    ->addSelect('ingrediente')
                    ->getQuery()
                    ->getOneOrNullResult()
               ;
    }
    public function queryByName($query)
    {
        $q = $this->createQueryBuilder('plato');
         
        return $q->add('where', $q->expr()->like('plato.name', sprintf('\'%%%s%%\'', $query)));
    }
    public function getPlatosByFechaPlan(\DateTime $fecha)
    {
        return $this->createQueryBuilder('plato')
                    ->leftJoin('plato.menus', 'menu')
                    ->leftJoin('menu.plan_momentos', 'plan_momento')
                    ->leftJoin('plan_momento.plan', 'plan')
                    ->where(sprintf('plan.fecha = \'%s\'', $fecha->format('Y-m-d')))
                    ->getQuery()
                    ->getResult()
               ;
    }
}
